eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8769
spring:
  application:
    name: server-zuul
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-consumer
    api-b:
      path: /api-a/**
      serviceId: service-feign
  #ignored-patterns: /**/m1/**
  prefix: /api
